# Generated by Django 5.0.3 on 2024-10-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunks', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
