# Generated by Django 5.0.3 on 2024-10-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chunks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
